### ISSUE TITLE
Error in Antibiotic resistance genes (ResFinder) count

### ISSUE THREAD

**Issue by alantsangmb** [nmquijada/tormes#2]
Hi, I am using tormes to analyse my four paired-end illumina data from 4 E. coli strains, and the final tormes_report.html report was generated.

In the section "Antibiotic resistance genes (ResFinder) count", the following Error is shown in the html file:

## Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : line 21 did not have 3 elements)
---------------------------------------------------------------------------------------------------------------
Resfinder could be executed without error and AMR genes could also be predicted and shown in the html file.

**Comment by nmquijada** [comment]
Hi,
It seems that the file used for the "Antibiotic resistance genes (ResFinder) count" is missing something and so the report rendering failed.
Would you mind sharing the "report_files.tgz" file?

**Comment by alantsangmb** [comment]
Please see the report files:
[report_files.zip](https://github.com/nmquijada/tormes/files/3275626/report_files.zip)

**Comment by nmquijada** [comment]
Hi,
Thanks for the comment and for sharing the data. Something failed by generating the "resfinder_gene_per_isolate.txt" file.
Find attached the "report_files" directory with the code in the "tormes_report.Rmd" from issue https://github.com/nmquijada/tormes/issues/3 already fixed, and also with a correct "resfinder_gene_per_isolate.txt" file and the html report.
The error regarding the "resfinder_gene_per_isolate.txt" file will be fixed in TORMES as soon as possible, together with a new release to conda.
Errors in the report can be fixed manually in the "tormes_report.Rmd" file, which can be used to re-render a new report in R environment. In the following days, I will add information of how to do it [here](https://github.com/nmquijada/tormes#rendering-customized-reports).
Thanks.
[report_files.zip](https://github.com/nmquijada/tormes/files/3285196/report_files.zip)

**Comment by alantsangmb** [comment]
Thank you!
