### ISSUE TITLE
folder assembly and genomes

### ISSUE THREAD

**Issue by valery-shap** [nmquijada/tormes#22]
Hello,

sorry but I don't clearly understand, what is the difference between folder assembly and genomes in output?
and one more question:
am I right that cleaned reads are only phred 33 and length 125, if there is no adapters?

Best regards,
Valery

**Comment by nmquijada** [comment]
Hi Valery,

The "assembly" directory contains the output from the assembly, that consist in the draft genome ("contigs.fasta") and many other intermediate files. Some of these files, such as the "assembly_graph.fastg", can be used by third party software, such as Unicycler (https://github.com/rrwick/Unicycler) for a deeper investigation of the genome. Thus, I decided to keep these files for those users willing to work with them. In order to decrease size, the assembly's output directory for each file is compressed.

The "genomes" directory, contains the draft genome after the assembly process (and so, included in the "assembly" directory), after removal of contigs <200 bp and renamed with the sample name. If a reference genome is used (```--reference``` option), the "genomes" directory will contain the genomes already ordered against that reference.

So, as a summary, the "genomes" directory contain the deffinitive genomes that will undergo downstream analysis. Having all genomes together in the same directory (even probably redundant), without other files, was deviced in an aesthetic perspective, for a quicker identification from the user. 

Your second question: when starting TORMES from raw reads, it only allows (by this time) paired-end data from Illumina platforms, an so Phred 33. The length = 125bp is set by default, but you can change it by using the ```--min_len``` parameter.

Best,
Narciso

**Comment by valery-shap** [comment]
Thank you very much for your answer. Now it is clear.
I can't find the article "TORMES: an automated pipeline for whole bacterial genome analysis." in open source. I've sent a request by researchgate but there is no answer. If it is not difficult for you, could you please send to me the paper?
Best regards,
Valery

**Comment by nmquijada** [comment]
Sure. Did you send the request to my user in researchgate? I don't see any new request.
Please send the request again and I will share the paper.
Best,
Narciso
