### ISSUE TITLE
which R and ggtree should be installed?

### ISSUE THREAD

**Issue by alantsangmb** [nmquijada/tormes#29]
Hi, I am trying to install the latest tormes 1.2.0 version 
But encounter the following error:

Quitting from lines 7-16 (tormes_report.Rmd)  
Error: package or namespace load failed for 'ggtree':  
package 'lattice' was installed by an R version with different internals; it needs to be reinstalled for use with this R version

Did I do something on the installation?
I used conda to install tormes 1.2.0 and ggtree.

Thanks

**Comment by nmquijada** [comment]
Hi @alantsangmb 
Did you run ```tormes-setup``` after installing TORMES with conda? This step will install ggtree by using BiocManager in R, as installing ggtree from conda had some issues.
Best,
Narciso

**Comment by alantsangmb** [comment]
I tried tormes-setup but encounter 'SSL connect error':

[TORMES]: Installing missing R packages

Bioconductor version 3.10 (BiocManager 1.30.10), ?BiocManager::install for help
Bioconductor version '3.10' is out-of-date; the current release version '3.11'
  is available with R version '4.0'; see https://bioconductor.org/install
Warning message:
In file(con, "r") :
  URL 'https://bioconductor.org/config.yaml': status was 'SSL connect error'
Bioconductor version 3.10 (BiocManager 1.30.10), R 3.6.3 (2020-02-29)
Bioconductor version 3.10 (BiocManager 1.30.10), ?BiocManager::install for help
Bioconductor version '3.10' is out-of-date; the current release version '3.11'
  is available with R version '4.0'; see https://bioconductor.org/install

I am running it behind a proxy, I am not sure if it is related.
So I tried to install ggtree separately using conda...

**Comment by nmquijada** [comment]
Hi @alantsangmb 
I set ggtree to be installed via BiocManager becasue with conda was not working properly. The other package that is installed this way is [treeio](https://www.bioconductor.org/packages/release/bioc/html/treeio.html). Without those two packages, ```tormes-report``` will not run.

Perhaps it would be better to try to solve the SSL connect error. It could be related to your proxy connection. I searched a bit and I found people running similar issues due to wrong set up of the ```https_proxy``` variable:

https://support.bioconductor.org/p/125812/
https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number

Can you try this?

**Comment by alantsangmb** [comment]
Thanks.

I've solved it by modifying the env variable. https_proxy=http://proxy.etc:8080

instead of https_proxy=https://proxy.etc:8080

**Comment by nmquijada** [comment]
Perfect! Glad that it worked!
