### ISSUE TITLE
fimH typing result not shown for the first isolate

### ISSUE THREAD

**Issue by alantsangmb** [nmquijada/tormes#3]
Hello, here is the output of the fimH_typing.txt in my analysis:

CR18000822	FimH type - E.coli
CR18000822b	FimH type - E.coli
ATCC25922one	FimH type: fimH30
ATCC25922nor	FimH type: fimH30

And all the 4 directories exist in the serotyping directory. However, when I inspect the tormes_report.html, the first result (CR18000822	FimH type - E.coli) is not included in the "Fim-H typing section".

**Comment by nmquijada** [comment]
Dear alantsangmb,

Really thanks for your comment. Indeed, there was an error in the R code rendering the fimH-typing ("header" needed to be set to "F"). The error will be fixed in TORMES as soon as possible.
Please find in your other issue (https://github.com/nmquijada/tormes/issues/2) the already corrected data.

**Comment by alantsangmb** [comment]
Thanks, looking forward for the next release of TORMES.
