### ISSUE TITLE
Looks error in renaming of ecoli_vf gene fedB (fedC protein) and fedC (fedD protein).

### ISSUE THREAD

**Issue by Vikash84** [nmquijada/tormes#41]
NODE_80 length_9008 cov_19.565139 | 5064 | 7478 | fedB | 0/0 | 100.0 | 100.0 | gi:15551735 | FedC protein

NODE_80 length_9008 cov_19.565139 | 4379 | 5071 | fedC | 0/0 | 100.0 | 100.0 | gi:15551736 | FedD protein

**Comment by nmquijada** [comment]
Hi @Vikash84 

So you are using the "ecoli_vf" database that is installed by default with tormes but not included in the main analysis (so you added it via ```--custom_genes_db``` flag.
This database belongs to the "Escherichia coli virulence factors" repository that you can find in https://github.com/phac-nml/ecoli_vf
It was automatically downloaded with ABRicate (https://github.com/tseemann/abricate) while installing tormes.

If you check the sequences and the information of the original database, you will see that the error is also there: https://raw.githubusercontent.com/phac-nml/ecoli_vf/master/data/repaired_ecoli_vfs.ffn

You can edit the fasta file with the information as you would like. Based on the path you wrote in your other issue (#40 ), the fasta file for your ecoli_vf database is: ```/home/miniconda3/envs/tormes-new/db/ecoli_vf/sequences```

So for instance, you can copy that file to your working directory, edit it manually (if you would like a quick script just for changing those two names let me know), and then install the "new" database:
```
# activate tormes environment first
cp /home/miniconda3/envs/tormes-new/db/ecoli_vf/sequences ecoli_vf_modif.fasta
# edit the ecoli_vf_modif.fasta file
# and generate the new database
tormes-install-custom-genes-db.sh -i ecoli_vf_modif.fasta -d ecoli_vf_modif
```

In your next tormes run, make sure to use the ```ecoli_vf_modif```` database instead of thw ```ecoli_vf```.

As this is an issue that is not internal of tormes but of the "Escherichia coli virulence factors" database, I suggest you to write an issue to its authors in their repository (https://github.com/phac-nml/ecoli_vf).

All the best,
Narciso
